---

# define build project project
# - name: Define path project
#   set_fact:
#       build_path: /opt/builds
#         tags:
#             - setup
#
#             - name: Validate build directory
#               file:
#                   path: '{{ build_path }}'
#                       state: directory
#                           mode: 0755
#                             tags:
#                                 - setup
#
#                                 - name: Define build project
#                                   set_fact:
#                                       build_project: "{{ build_project }}"
#                                         tags:
#                                             - setup
#
#                                             - name: Define environment variable
#                                               set_fact:
#                                                   env: "{{ env }}"
#                                                     tags:
#                                                         - setup
#
#                                                         - name: Define deploy key
#                                                           set_fact:
#                                                               deploy_key: "/opt/keys/enve.key"
#                                                                 tags:
#                                                                     - setup
#
#                                                                     # pull API code
#                                                                     - name: Pull {{ build_project }} for enve
#                                                                       shell: |
#                                                                           cd {{ build_path }}
#                                                                               if [ -d {{ build_project }} ]
#                                                                                   then
#                                                                                         sudo rm -fr {{ build_project }}
#                                                                                             fi
#                                                                                                 sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git clone git@github.com:david-enve/projects.git --depth 1 --branch {{ branch }} 
#                                                                                                   delegate_to: localhost
#                                                                                                     run_once: true
#                                                                                                       tags: 
#                                                                                                           - update
#
#                                                                                                           # find artifacts and store its path
#                                                                                                           - name: Find artifacts in order to deploy against EI nodes
#                                                                                                             find: paths="{{ build_path }}/{{ build_project }}" recurse=yes patterns="*.txt"
#                                                                                                               register: artifacts
#                                                                                                                 delegate_to: localhost
#                                                                                                                   tags:
#                                                                                                                       - update
#

