---

# define build project project
- name: Define path project
  set_fact:
    build_path: /opt/builds
  tags:
    - setup

- name: Validate build directory
  file:
    path: '{{ build_path }}'
    state: directory
    mode: 0755
  tags:
    - setup

- name: Define build project
  set_fact:
    build_project: "{{ build_project }}"
  tags:
    - setup

- name: Define environment variable
  set_fact:
    env: "{{ env }}"
  tags:
    - setup

- name: Define deploy key
  set_fact:
    deploy_key: "/opt/keys/enve.key"
  tags:
    - setup

# pull code from project
- name: Pull {{ build_project }} for enve project from  {{ branch }}
  shell: |
    cd {{ build_path }}/{{ build_project }} 
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git clone git@github.com:david-enve/projects.git --branch {{ branch }} 
  delegate_to: localhost
  run_once: true
  tags: 
    - update

# pull code from {{ merge_branch }} in order to do a merge
- name: Pull {{ build_project }} from {{ merge_branch }}
  shell: |
    cd {{ build_path }}/{{ build_project }}
    sudo git checkout -b {{ merge_branch }} 
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git pull git@github.com:david-enve/projects.git {{ merge_branch }}:{{ local_branch }}
  delegate_to: localhost
  run_once: true
  tags: 
    - update
    
# Merge code into {{ branch }}
- name: merge code from {{ merge_branch }} into {{ branch }}
  shell: |
    cd {{ build_path }}/{{ build_project }}
    git checkout {{ branch }}
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git merge {{ merge_branch }} 
  delegate_to: localhost
  run_once: true
  tags: 
    - update
    
# Push merged code to project repository 
- name: Push merged code to {{ branch }} for enve project repository
  shell: |
    cd {{ build_path }}/{{ build_project }}
    git checkout {{ branch }}
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git push 
  delegate_to: localhost
  run_once: true
  tags: 
    - update 
