---

- name: Define environment variable
  set_fact:
    env: "{{ env }}"
  tags:
    - setup

- name: Define deploy key
  set_fact:
    deploy_key: "/opt/keys/enve.key"
  tags:
    - setup

# pull API code
- name: Pull {{ build_project }} for enve
  shell: |
    cd {{ build_path }}/{{ build_project }} 
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git clone git@github.com:david-enve/projects.git --depth 1 --branch {{ branch }} 
  delegate_to: localhost
  run_once: true
  tags: 
    - update

# Merge code 
- name: Pull {{ build_project }} for enve
  shell: |
    cd {{ build_path }}/{{ build_project }}
    sudo git checkout {{ env }}
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git merge develop 
  delegate_to: localhost
  run_once: true
  tags: 
    - update
