---

# define build project project
- name: Define path project
  set_fact:
    build_path: /opt/builds
  tags:
    - setup

- name: Validate build directory
  file:
    path: '{{ build_path }}'
    state: directory
    mode: 0755
  tags:
    - setup

- name: Define build project
  set_fact:
    build_project: "{{ build_project }}"
  tags:
    - setup

- name: Define environment variable
  set_fact:
    env: "{{ env }}"
  tags:
    - setup

- name: Define deploy key
  set_fact:
    deploy_key: "/opt/keys/enve.key"
  tags:
    - setup

# pull API code
- name: Pull {{ build_project }} for enve
  shell: |
    cd {{ build_path }}/{{ build_project }} 
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git clone git@github.com:david-enve/projects.git --depth 1 --branch {{ branch }} 
  delegate_to: localhost
  run_once: true
  tags: 
    - update

# Merge code 
- name: Pull {{ build_project }} for develop branch
  shell: |
    cd {{ build_path }}/{{ build_project }}
    sudo git checkout {{ branch }}
    sudo git checkout -b develop 
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git pull git@github.com:david-enve/projects.git develop:develop
  delegate_to: localhost
  run_once: true
  tags: 
    - update
    
# Merge code 
- name: Merge develop code in {{ branch }}
  shell: |
    cd {{ build_path }}/{{ build_project }}
    git checkout release
    sudo GIT_SSH_COMMAND="ssh -i {{ deploy_key }} -o StrictHostKeyChecking=no -F /dev/null" git merge develop 
  delegate_to: localhost
  run_once: true
  tags: 
    - update
    
    
